### ISSUE TITLE
Circular progress aria value

### ISSUE THREAD

**Issue by lasseklovstad** [Altinn/altinn-design-system#125]
### Description of the bug

When using a screen reader and the value of the circular progress was a decimal number the screen reader would read the whole decimal number even though it is veeeery long.

### Steps To Reproduce

1. go to circular progress
2. Use a screen reader (Feks NVDA) to read the circualr progress.

**Comment by haakemon** [comment]
Released in https://github.com/Altinn/altinn-design-system/releases/tag/v0.8.1
