### ISSUE TITLE
Accordion fix

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-design-system#128]
Accordion must be adjusted a bit. E.g. Center accordion header text vertically when component is imported by other projects. Accordion also needs to enable having at least 2 separate(But having support for at least ) buttons in it instead of just 1. There's also some padding/margin in accordion button that should probably should be fixed. Also support subText like picture below.
<img width="388" alt="image" src="https://user-images.githubusercontent.com/31471142/192277698-2bcd6d1e-2f79-4320-b696-64c28abec906.png">

<h3>Tasks</h3>

- [x] Support for two buttons
- [x] Support for subtext
- [x] Support for end text
- [x] Adjust icon padding (previously off when no buttons added)
- [x] Added support for showcasing new features in Storybook
- [x] Current tests work
- [x] Write new tests

**Comment by hannekristin** [comment]
Designreview ok
