### ISSUE TITLE
Table component

### ISSUE THREAD

**Issue by Febakke** [Altinn/altinn-design-system#129]
### Description

The first iteration on our table component.

## Proposed features
- Header rows and columns
- Be able to select one row
- sorting
- searching
- paging

**Comment by olemartinorg** [comment]
Implemented in the design system now. [See storybook here](https://designsystem.altinn.studio/?path=/story/components-table--basic-table).

Related PRs:
- #164 
- #187
- #207
- #211 
- #213
- #223
- #242
- #252

All proposed features from the list above has been implemented, apart from search, as that functionality is not relevant to the design system (it does not have any distinct visual component). We have #148, which lets you add a search field _outside_ the table and have that affect which rows are visible in the table - but that's up to you when implementing the component from the design system.
