### ISSUE TITLE
Multiple Select component

### ISSUE THREAD

**Issue by lorang92** [Altinn/altinn-design-system#138]
### Description

Multiple select component described in [Figma ](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/DDS---Core-Components?node-id=7538%3A45627)should be implemented. This component has partially been implemented in app-frontend repo in the PR https://github.com/Altinn/app-frontend-react/pull/505. Some code might be reused.

![image](https://user-images.githubusercontent.com/10416981/193289824-8bf90eb5-58e9-408d-9e78-d8248d56ac1a.png)

### Additional Information

Once the component has been implemented, we should replace existing implementation in app-frontend. See issue https://github.com/Altinn/app-frontend-react/issues/510

### Tasks

- [ ] Implement
- [ ] Design review

### Acceptance Criterias

- Multiple select is implemented
- ...

**Comment by TomasEng** [comment]
Waiting for Figma tokens in order to continue working on this.

**Comment by TomasEng** [comment]
Closing this as I have created new issues for the remaining tasks:
- #201 
- #202
