### ISSUE TITLE
Add label to SearchField, TextArea and TextField

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-design-system#162]
### Description

These components should get a nullable label prop and should look like in the picture below and [DDS](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/DDS---Core-Components?node-id=6632%3A22123)
![image](https://user-images.githubusercontent.com/31471142/197470899-1cd04241-12b4-434f-b4bf-c78ae0e8d4f6.png)

**Comment by hannekristin** [comment]
Er det ikke meningen at jeg skal kunne se dette i storybook nå @allinox ?

**Comment by allinox** [comment]
Det skal ligge ute nå @hannekristin 😊

**Comment by hannekristin** [comment]
Flott. Da er den ok
