### ISSUE TITLE
Create radio buttons component

### ISSUE THREAD

**Issue by TomasEng** [Altinn/altinn-design-system#209]
We should add a radio buttons component to the design system as soon as [the sketch](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/DDS---Core-Components?node-id=9066%3A48225&t=6xW8qKhXSxPJG2uQ-0) is finished.

**Comment by bjosttveit** [comment]
Also needed for `app-frontend-react` by team apps!
