### ISSUE TITLE
Toggle button group | Commodore

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-design-system#24]
We need a toogle switch like in the picture below for various panels in https://www.altinn.no/ui/Profile
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/31471142/170265632-d98ddde9-72bd-4155-99b8-eaeb5f3e6e23.png">

It should be developed with inspiration from material ui and NAV design system.

In the figma file it says that the component should only be used with two buttons and it can be smart to do it with this approach as well because it can cause screen breakpoint issues if we make it optional to have more than two buttons or as many buttons as a person want.

~It should perhaps support having icons in the buttons as well.~ - this should be added later if/when we have a usecase for it.

**Comment by haakemon** [comment]
> It should perhaps support having icons in the buttons as well.
Lets not worry about this until we have a usecase for it :)
