### ISSUE TITLE
Figma tokens - Toggle button component

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-design-system#33]
We need some figma tokens. The tokens we currently are in need of is listed below.
![75236449-1D17-4D4E-9991-AACF30734648](https://user-images.githubusercontent.com/31471142/174610351-a1c70a17-bf34-44a9-8f3d-575caa0d40db.jpeg)

![image](https://user-images.githubusercontent.com/31471142/174609840-448fbfc6-e46c-4608-a8b9-3ce0db59c317.png)

**Toggle button:**
Is the buttons themself

- component-toggle-button-space-padding-left-right
- component-toggle-button-space-padding-top-bottom
- toggle-button-border-width
- toggle-button-border-radius
- toggle-button-border-style
- toggle-button-font-size
- toggle-button-min-width

Toggle button for phone screens/smaller screens:

- component-toggle-button-space-padding-left-right-sm
- component-toggle-button-space-padding-top-bottom-sm
- toggle-button-border-wdith-sm
- toggle-button-border-radius-sm
- toggle-button-border-style-sm
- toggle-button-font-size-sm
- toggle-button-button-min-width-sm

**Toggle button group**
Is the component that contains the toggle buttons. It is f.ex. Used to have 1 blue border around both toggle buttons.

- component-toggle-button-group-border-width
- component-toggle-button-group-border-style
- component-toggle-button-border-color

**Comment by Albertlarsen** [comment]
Example comment
Toggle button:

--component-toggle-button-space-padding-left-right | component-toggle-button-space-padding-left-right
--component-toggle-button-space-padding-top-bottom 
--toggle-button-border-wdith
--toggle-button-border-radius | button-border-radius
--toggle-button-border-style
--toggle-button-font-size
--toggle-button-button-min-width

Toggle button for phone screens/smaller screens:

--component-toggle-button-space-padding-left-right-sm
--component-toggle-button-space-padding-top-bottom-sm
--toggle-button-border-wdith-sm
--toggle-button-border-radius-sm
--toggle-button-border-style-sm
--toggle-button-font-size-sm
--toggle-button-button-min-width-sm

Toggle button group

--component-toggle-button-group-border-width
--component-toggle-button-group-border-style
--component-toggle-button-border-color

**Comment by Albertlarsen** [comment]
Toggle button:

--component-toggle-button-space-padding-left-right | --component-toggle-button-space-padding-vertical
--component-toggle-button-space-padding-top-bottom
--toggle-button-border-wdith
--toggle-button-border-radius
--toggle-button-border-style
--toggle-button-font-size
--toggle-button-button-min-width

Toggle button for phone screens/smaller screens:

--component-toggle-button-space-padding-left-right-sm
--component-toggle-button-space-padding-top-bottom-sm
--toggle-button-border-wdith-sm
--toggle-button-border-radius-sm
--toggle-button-border-style-sm
--toggle-button-font-size-sm
--toggle-button-button-min-width-sm

Toggle button group

--component-toggle-button-group-border-width
--component-toggle-button-group-border-style
--component-toggle-button-border-color

**Comment by Albertlarsen** [comment]
Toggle button:
Is the buttons themself

- component-toggle-button-space-padding-left-right | component-toggle-button-space-padding-horizontal
- component-toggle-button-space-padding-top-bottom
- toggle-button-border-width
- toggle-button-border-radius
- toggle-button-border-style | toggle-button-border
- toggle-button-font-size
- toggle-button-min-width
- Toggle button for phone screens/smaller screens:

- component-toggle-button-space-padding-left-right-sm
- component-toggle-button-space-padding-top-bottom-sm
- toggle-button-border-wdith-sm
- toggle-button-border-radius-sm
- toggle-button-border-style-sm
- toggle-button-font-size-sm
- toggle-button-button-min-width-sm

Toggle button group
Is the component that contains the toggle buttons. It is f.ex. Used to have 1 blue border around both toggle buttons.

- component-toggle-button-group-border-width
- component-toggle-button-group-border-style
- component-toggle-button-border-color

**Comment by mrosvik** [comment]
Toggle button:
Is the buttons themself

~~component-toggle-button-space-padding-left-right~~  component-toggle-space-padding-x
~~component-toggle-button-space-padding-top-bottom~~ component-toggle-space-padding-bottom
~~toggle-button-border-width~~ component-toggle-borderWidth-deactive
~~toggle-button-border-radius~~ (don't exist)
~~toggle-button-border-style~~ (don't exist)
~~toggle-button-font-size~~ component-toggle-font-size-xs
~~toggle-button-min-width~~ component-toggle-size-minWidth-sm 

~~Toggle button for phone screens/smaller screens:~~
~~Toggle button for larger screens:~~ (mobile first)

~~component-toggle-button-space-padding-left-right-sm~~ (not necessary, same for all breakpoints)
~~component-toggle-button-space-padding-top-bottom-sm~~ (not necessary, same for all breakpoints)
~~toggle-button-border-wdith-sm~~ (not necessary, same for all breakpoints)
~~toggle-button-border-radius-sm~~  (don't exist)
~~toggle-button-border-style-sm~~  (don't exist)
~~toggle-button-font-size-sm~~ component-toggle-font-size-md / lg / xl
~~toggle-button-button-min-width-sm~~ component-toggle-size-minWidth-md

Toggle button group
Is the component that contains the toggle buttons. It is f.ex. Used to have 1 blue border around both toggle buttons.

~~component-toggle-button-group-border-width~~ (styled on deactive part)
~~component-toggle-button-group-border-style~~ (styled on deactive part)
~~component-toggle-button-border-color~~  (styled on deactive part)

**Comment by mrosvik** [comment]
`"toggle_button": {
      "font_size": {
        "xs": {
          "value": "{font_size.body.xs}",
          "type": "fontSizes"
        },
        "md": {
          "value": "{font_size.body.md}",
          "type": "fontSizes"
        },
        "lg": {
          "value": "{font_size.body.lg}",
          "type": "fontSizes"
        },
        "xl": {
          "value": "{font_size.body.xl}",
          "type": "fontSizes"
        }
      },
      "size": {
        "min_width": {
          "sm": {
            "value": "100%",
            "type": "sizing"
          },
          "md": {
            "value": "auto",
            "type": "sizing"
          }
        }
      },
      "border_width": {
        "deactive": {
          "value": "2px",
          "type": "borderWidth"
        }
      },
      "color": {
        "background": {
          "active": {
            "value": "{colors.interaction.default}",
            "type": "color"
          },
          "deactive": {
            "value": "{colors.white}",
            "type": "color"
          }
        },
        "text": {
          "active": {
            "value": "{colors.white}",
            "type": "color"
          },
          "deactive": {
            "value": "{colors.black}",
            "type": "color"
          }
        },
        "border": {
          "deactive": {
            "value": "{colors.interaction.default}",
            "type": "color"
          }
        }
      },
      "space": {
        "padding": {
          "x": {
            "value": "{space.x2}rem",
            "type": "spacing"
          },
          "top": {
            "value": "0.125rem",
            "type": "spacing"
          },
          "bottom": {
            "value": "0.25rem",
            "type": "spacing"
          }
        }
      }
    },`

**Comment by mrosvik** [comment]
"toggle_button": {
      "font_size": {
        "xs": {
          "value": "{font_size.body.xs}",
          "type": "fontSizes"
        },
        "md": {
          "value": "{font_size.body.md}",
          "type": "fontSizes"
        },
        "lg": {
          "value": "{font_size.body.lg}",
          "type": "fontSizes"
        },
        "xl": {
          "value": "{font_size.body.xl}",
          "type": "fontSizes"
        }
      },
      "size": {
        "min_width": {
          "sm": {
            "value": "100%",
            "type": "sizing"
          },
          "md": {
            "value": "auto",
            "type": "sizing"
          }
        }
      },
      "border_width": {
        "deactive": {
          "value": "2px",
          "type": "borderWidth"
        }
      },
      "color": {
        "background": {
          "active": {
            "value": "{colors.interaction.default}",
            "type": "color"
          },
          "deactive": {
            "value": "{colors.white}",
            "type": "color"
          }
        },
        "text": {
          "active": {
            "value": "{colors.white}",
            "type": "color"
          },
          "deactive": {
            "value": "{colors.black}",
            "type": "color"
          }
        },
        "border": {
          "deactive": {
            "value": "{colors.interaction.default}",
            "type": "color"
          }
        }
      },
      "space": {
        "padding": {
          "x": {
            "value": "{space.x2}rem",
            "type": "spacing"
          },
          "top": {
            "value": "0.125rem",
            "type": "spacing"
          },
          "bottom": {
            "value": "0.25rem",
            "type": "spacing"
          }
        }
      }
    },

**Comment by mrosvik** [comment]
Updated previous comment with the new tokens.
