### ISSUE TITLE
Panel component layout overflows when used in small containers

### ISSUE THREAD

**Issue by haakemon** [Altinn/altinn-design-system#36]
### Description of the bug

As you can see in the below screenshot, the available space in a size 4 grid is very little because of the padding size:
![image](https://user-images.githubusercontent.com/2082481/172826709-5662a3d9-e2fa-48da-a2da-0d0764d4e1e3.png)

### Steps To Reproduce

Can easiest be reproduced by spinning up the [soft-validations-v2 app](https://altinn.studio/repos/ttd/soft-validations-v2), and typing "info" into the box at the bottom

### Additional Information

A potential fix is to [utilize `min()` css function](https://developer.mozilla.org/en-US/docs/Web/CSS/min) to select the smallest size of the listed options, f.ex

```css
.Panel-module_panel__content-wrapper {
  padding-left: min(var(--panel-left-padding), 10%);
  padding-right: min(var(--panel-right-padding), 10%);
}
```

this will make the padding 10% when `--panel-left-padding` is greater than 10% of the width of the component. 10% was used to not interfere when the component is rendered in Altinn Studio at 100% of the page width.

With these changes, there is much more space available:
![image](https://user-images.githubusercontent.com/2082481/172828425-bdec668b-01e5-4f79-92eb-f48f79226fe6.png)
But as we can see it still overflows, but this depends a bit on the length of the longest word within the body content. Additional space can be saved by hiding the icon, or reducing its size.

Another potential solution would be to inspect the rendered size of the component, and if its smaller than X (f.ex 300px), reduce padding and icon size. The downside of this solution is that the component would be rendered several times, because we cannot do the initial check before it has already rendered.

**Comment by haakemon** [comment]
@mrosvik Do you have any input on how this should look when used in small containers? Should it just look like the mobile version?

**Comment by mrosvik** [comment]
@haakemon The panel should fill the whole width of the modal. 
![image](https://user-images.githubusercontent.com/1464915/173000865-7ab65c50-06d8-4979-b82d-137fedb75768.png)

**Comment by haakemon** [comment]
My initial suggestion did not work well after all, since I didnt think about the responsiveness on the page itself. With that approach and when resizing the viewport to be smaller than our max-width, the padding would be too small for the infopanel that stretches all 12 columns.

The approach with using `useLayoutEffect` is not ideal either, because of the render issues mentioned.

We instead decided to go for a solution where we can force the Panel to be viewed in "mobile mode", so we can get a version with smaller padding also on large viewports, depending on where its used.
