### ISSUE TITLE
Table component

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-design-system#39]
On hold until further notice. We need a table component like the one that's in red in the pic below. It should be able to be used inside an accordion(and other relevant components) like in the picture below.

Proposed architecture:

Other stuff to think about:

1. Responsive design

![image](https://user-images.githubusercontent.com/31471142/174026858-46cf3949-cfa2-40e1-8574-3cd16965c488.png)

**Comment by olemartinorg** [comment]
Duplicate of #129, or is this supposed to be another component?
Also, tables are [already implemented](https://designsystem.altinn.studio/?path=/story/components-table--basic-table), and a responsive table is on the way now (#252). Should we close this issue?

**Comment by Albertlarsen** [comment]
@olemartinorg Yes, this is a really old issue that was written when we only had 2 components and no table component in FDS. I'll close this. Thanks for going through this though 😊
