### ISSUE TITLE
Add icons

### ISSUE THREAD

**Issue by haakemon** [Altinn/altinn-design-system#43]
### Description

We have a need for icons in many of our components, and we dont want to use font-icons for this because it has some problems (font not loading, font loading slowly, etc...)

We would like to use SVG icons.

The icons should be designed:
- on a 36*36px grid
- as a single path (can we flatten the icons programatically? if not, it needs to be modified before export)
- 2px gap between icon and grid
- ... all design rules are listed in Figma: https://www.figma.com/file/hGQZ5IiihuCIstjKFpv0YQ/ADS-3---Ressurser?node-id=110%3A16

Other major icon libraries are also doing it in a very similar way, f.ex https://materialdesignicons.com

### Additional Information

By enforcing designs to only contain 1 path element, its easier to enforce certain rules programatically, and it is also possible to export icons as "path strings" instead of complex components. The downsides are that it will only be possible with monocolor icons, and no animations within the icon. If we have a need for multicolor icons, or icons with animations, they need to be handled separately. 

Example SVG export from Figma:
```svg
<svg width="36" height="36" viewBox="0 0 36 36" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M11.5228 34L10 32.4762L24.6566 18L10 3.52381L11.5228 2L27.3214 18L11.5228 34Z" fill="black"/>
</svg>
```

There are a couple problems with this icon. There is a fixed `width` and `height` on the SVG element, which makes it impossible to override this via css without using `!important`. There is also a fixed `fill` on the `path` element, which makes it impossible to override the color of the icon without using `!important`. These problems could be fixed by manually editing the file after export, or running them through a tool like SVGO to automatically clean up the code. But it still leaves us with a complex object we need to deal with.

If we instead extract the `d` attribute of the `path`, we can export all icons represented as a string:

```tsx
const arrowRight = "M11.5228 34L10 32.4762L24.6566 18L10 3.52381L11.5228 2L27.3214 18L11.5228 34Z";
```
and the rest of the implementation can be done as a React component:

```tsx
const Icon = (path: string) => {
  return (
    <svg viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg">
      <path d={path} />
    </svg>);
}
```

In our icon library we have 2 weights of the icons. By using this approach, we can also easily increase the weight, instead of having several SVG's with different weights, by doing something like:

```tsx
type IconProps = {
  path: string;
  weight?: Weight;
};

const Icon = ({ path, weight = Weight.Regular }: IconProps) => {
  const strokeProps =
    weight === Weight.Bold
      ? {
          stroke: "currentColor",
          strokeWidth: 1
        }
      : {};

  return (
    <svg viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg">
      <path d={path} {...strokeProps} />
    </svg>
  );
};
```

**Comment by haakemon** [comment]
Setting status back to draft, because we might use an external library instead, and this approach may not be what we end up with.

**Comment by andrealouisestanderen** [comment]
Closing this issue since the decision fell on using NAVs icons.
