### ISSUE TITLE
Change Altinn font to Inter on all relevant products

### ISSUE THREAD

**Issue by Febakke** [Altinn/altinn-design-system#51]
### Description

Because of lisens issues and lacking functionality on FF DIN and Altinn-DIN we have to find one font that we can use on all our products. After reviewing different potensial Open Source fonts we landed on [Inter](https://rsms.me/inter/) as the best solution.

This epic should track changing font on all relevant pages, also those that are outside this design system.

 

### In scope

Define the different weights and sizes we need to replace FF DIN 
Test how the different pages will look/behave after a font change
Change the font on relevant pages/systems

**Comment by mrosvik** [comment]
Replaced by https://github.com/orgs/digdir/projects/3/views/1?pane=issue&itemId=17434542
