### ISSUE TITLE
Page component

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-design-system#57]
This issue is on hold until further notice.
The feature should support different Page variants (primary and success) seen in the pics below. Height and width: 100%. Icon should be free of choice with set height and width based on the Page size. CardHeader Text color should be set according to Page variant. We need a big Page for big screen and a small Page for small screen which can be seen here: https://www.figma.com/file/ESobgAq072y7eQa4gP1JCKER/Profil?node-id=1209%3A8163
and here: https://www.figma.com/file/ESobgAq072y7eQa4gP1JCKER/Profil?node-id=3750%3A61907

![image](https://user-images.githubusercontent.com/31471142/176898599-fe47048d-e672-4a22-90af-8a7772905e81.png)
![image](https://user-images.githubusercontent.com/31471142/183035827-f90a3923-5520-4fa6-b5dc-b5f250687078.png)
![image](https://user-images.githubusercontent.com/31471142/183589386-9c410e8a-4219-4b17-819e-da4ad9b31c10.png)

Architecture:
Page - PageHader - PageContent

### Description
Simple description of component

### Figma
_Link to correct placement in our Figma component library._
- [x] Check if there are similar components/variants from Altinn 2, Altinn Studio or Altinn 3 that need to be considered. 
- [x] Are there any WCAG issues with the component
- [x] Component is created in Figma
- [x] All relevant states are created
- [x] Functionality/animation is described and prototyped 

### Tokens
- [ ] The size is described with tokens
- [ ] spacing is described with tokens
- [ ] The color of all states are described with tokens
- [ ] Border width or styling is described with tokens
- [ ] Text size are described with tokens

```
Replace with size tokens

Replace with padding

Replace with colors

Replace with border width

Replace with text
```

### SVG
- [x] If there are used any svgs in this component is it available for the developer?

**Comment by haakemon** [comment]
@Albertlarsen What is the usecase for customizable header color and background?

@Febakke Do we have design system specs for this yet?

**Comment by Albertlarsen** [comment]
> @Albertlarsen What is the usecase for customizable header color and background?
> 

@haakemon Perhaps customizable header color and background isn't the right wording for this but what I meant was that the code should support different card variants (right now the only variant we need is the one with the blue header and white content) and maybe also an unstyled headless variant. Unless we are going to be strict about using unstyled components.

Also to be clear I want to state that thos should be a general card component, meaning that the content of the is something that shouldn't be preset. See the attached photo. 
<img width="737" alt="image" src="https://user-images.githubusercontent.com/31471142/182116503-c8901bd0-d8f5-451f-8bb4-ff6a07b52456.png">

**Comment by haakemon** [comment]
Ok. I dont think we should add an "unstyled"-variant then. Start with what we need right now (the blue header). If we need another one (with f.ex grey header) that can be added later. I'm not sure a completely unstyled variant is something we should introduce to our design system library.

I agree the content has to be something that the consumer provides.

**Comment by Albertlarsen** [comment]
Allright, I'll remove unstyled variant in another component I'm working with as well
