### ISSUE TITLE
TextArea component

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-design-system#59]
### Description
We need a text field like the one in the picture. Pay attention to the dragable size button that is pointed to.
![image](https://user-images.githubusercontent.com/31471142/176900690-1e8d18ab-7737-418f-a97c-781b13280cdf.png)

### Figma
[_Link to correct placement in our Figma component library._](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/DDS---Core-Components?node-id=6632%3A21857)

<img width="2251" alt="image" src="https://user-images.githubusercontent.com/1464915/190493902-933ef9ab-1025-458e-b88f-d9b657680dc8.png">

### Specification
- Text area should have a label and it should be possible to add an additional description on several lines under label.
- It should be possible to add a character count. 
- The width is 100% inside the grid its placed in. It comes in different heights. The height that matches the expected user input should be used. 
- Read-only should as default be plain text, but could be highlighted with an extra css-class for specific cases. See guidelines in Figma. 

### Design tasks
- [x] Component is created in Figma
- [x] All relevant states are created
- [x] Functionality/animation is described and prototyped 
- [x] The disabled / read-only should be handled equally on all components, find something that works across.

### Tokens
- [x] The size is described with tokens
- [x] spacing is described with tokens
- [x] The color of all states are described with tokens
- [x] Border width or styling is described with tokens
- [x] Text size are described with tokens

```
Size
Sets min-height: 
component-textarea-size-min_height-xsmall
component-textarea-size-min_height-small
component-textarea-size-min_height-medium
component-textarea-size-min_height-large
component-textarea-size-min_height-xlarge

-------

Space
Sets padding x and y:
component-textarea-space-padding-x
component-textarea-space-padding-y

-------

Color
Sets border color:
component-textarea-color-border-default
component-textarea-color-border-hover
component-textarea-color-border-disabled
component-textarea-color-border-read-only

Sets background color:
component-textarea-color-background-default
component-textarea-color-background-read-only

Sets text-color:
component-textarea-color-text-default
component-textarea-color-text-disabled 

Sets outline color for focus:
interactive_components-colors-focus_outline

-------

Font Size
Sets font-size:
component-textarea-font_size-default

-------

Border width
interactive_components-border_width-normal 

-------

Border radius
interactive_components-border_radius-normal
 

```

### SVG
- [ ] If there are used any svgs in this component is it available for the developer?

**Comment by mrosvik** [comment]
Status: Standard states and types are finished, but the disabled / read-only state may change as we have to handle this equally on all components, and we should find something that works across. 

Do we need a larger text area variant with WYSIWYG editor for studio? Should that be a variant of this component or a different component? @haakemon

**Comment by haakemon** [comment]
Good work on this 😁

Yes, we will need some WYSIWYG editor with markdown support for Studio. I think that should be a separate component.

**Comment by FinnurO** [comment]
Would this be the time to introduce/include a character count? https://github.com/Altinn/altinn-studio/issues/1116

**Comment by mrosvik** [comment]
Text area is ready for Review and development.
