### ISSUE TITLE
Document how to add new dependencies

### ISSUE THREAD

**Issue by haakemon** [Altinn/altinn-design-system#62]
### Description

If we dont add new dependencies to the `exclude` list in rollup config, then the dependency will be bundled. This is in most cases not what we want - we want the dependency to be resolved automatically where the package is used.

Related comment https://github.com/Altinn/altinn-design-system/pull/60#discussion_r915546682

### Additional Information

Could also look into if there exists a rollup plugin to handle this automatically, similar to how peerDependencies are handled

### Acceptance Criterias

- [x] Document that when adding a new dependency to package.json, you also have to update exclude list in rollup config
OR
- [ ] Find a plugin that will deal with this automatically

The end result should be the same - items in `dependencies` in package.json should not be part of the generated bundle.

**Comment by olemartinorg** [comment]
This is the code I've been using in another project to exclude packages:

```javascript
import pkg from 'package.json';

const externals = []
    .concat(Object.keys(pkg.dependencies))
    .concat(Object.keys(pkg.devDependencies))
    .concat(require('module').builtinModules || Object.keys(process.binding('natives')));
```

**Comment by haakemon** [comment]
https://github.com/Altinn/altinn-design-system#adding-new-dependencies
