### ISSUE TITLE
Checkbox component

### ISSUE THREAD

**Issue by haakemon** [Altinn/altinn-design-system#86]
### Description
We need a basic checkbox component.

### Figma
[Figma link](https://www.figma.com/file/d1VzAmoVdredZkky139AIT/ADS-3---Komponenter?node-id=190%3A13783) 

![image.png](https://images.zenhubusercontent.com/5cfa06c0f0faa828c49c2348/8ba4843e-e6a5-42fc-b816-cd62695837e9)

- [x] Component is created in Figma
- [x] All relevant states are created
- [x] Functionality/animation is described and prototyped / No animation or other functionality other than checked/uncheced

### Tokens
- [x] The size is described with tokens
- [x] spacing is described with tokens
- [x] The color of all states are described with tokens
- [x] Border width or styling is described with tokens
- [x] Text size are described with tokens

```
Design tokens 

Size
Sets width and height for normal checkboxes to 24px:
component-checkbox-size-width-normal
component-checkbox-size-height-normal 

Sets width and height for compact checkboxes to 18px:
component-checkbox-size-width-compact
component-checkbox-size-height-compact

-------

Space
Sets gap between box and text to 12px for normal checkboxes:
component-checkbox-space-gap-normal 

Sets gap between box and text to 8px for compact checkboxes:
component-checkbox-space-gap-compact

-------

Color
Sets border-color for states default, hover, error:
component-checkbox-color-border-default
component-checkbox-color-border-hover
component-checkbox-color-border-checked
component-checkbox-color-border-disabled
component-checkbox-color-border-error

Sets background-color for states default, hover and focus:
component-checkbox-color-background-default
component-checkbox-color-background-hover
component-checkbox-color-background-checked
component-checkbox-color-background-error

Sets text-color for for states default, hover, error, focus:
component-checkbox-color-text-default
component-checkbox-color-text-hover
component-checkbox-color-text-checked
component-checkbox-color-text-error
component-checkbox-color-text-disabled

Sets outline color for tab-focus:
interactive_components-colors-focus_outline

-------

Border width
Sets border-width for normal and compact type
component-checkbox-border_width-normal
component-checkbox-border_width-compact

------- 
Font Size
Sets font-size for normal and compact type
component-checkbox-font_size-normal
component-checkbox-font_size-compact






```

### SVG
- [x] If there are used any svgs in this component is it available for the developer?

There is a checkmark svg, one for normal view, and one for compact view:

![check-symbol-compact](https://user-images.githubusercontent.com/1464915/184026336-589f469d-a10e-4806-87ad-0ef4c16744e6.svg)
![check-symbol-normal](https://user-images.githubusercontent.com/1464915/184026341-aaaa8f0b-c4c6-4932-b51e-c9bf478745eb.svg)

**Comment by RonnyB71** [comment]
Missing readonly and disabled state. cc: @mrosvik

**Comment by mrosvik** [comment]
- Added correct styling that matches how we define hover and focus on other interactive elements.
- Added disabled and read-only state (NB: should come with a warning explaining why user can´t edit! (See example))
- Added compact view for checkboxes
- Added example with horizontal and vertical group
- New Design Tokens are described in Figma
- Uploaded svg icon for check symbol into description of this issue (normal and compact view, containing the correct space around symbol)
- Added component properties to set checked/unchecked state in Figma. 
- Updated guidelines in Figma for the component. 

- [ ] Legend and description has to be created with correct tokens. 
- [ ] Create tokens for disabled/read-only

**Comment by haakemon** [comment]
@mrosvik regarding the icon, my initial thought is to use the same icon for normal view and compact view, but resize the icon with css for compact view. If we go with that approach, we would need a size token for the icon as well. Or perhaps we can just calculate it based on the checkbox size, since we already have that information?

**Comment by mrosvik** [comment]
@haakemon I can add a size token for the icon normal and compact view.
