### ISSUE TITLE
Warning modal component

### ISSUE THREAD

**Issue by lorang92** [Altinn/altinn-design-system#97]
### Description

For repeating groups there is a need to display a warning modal when deleting large items. See issue https://github.com/Altinn/app-frontend-react/issues/321. We should implement a modal that can be used for this case.

### Additional Information

![image](https://user-images.githubusercontent.com/10416981/185073504-fc7c90f6-a261-4812-9555-a8036f3f2256.png)

**Comment by Magnusrm** [comment]
This seems to be related to the popover component being developed in the design system and can probably be implemented using that component. https://github.com/Altinn/altinn-design-system/issues/58

**Comment by haakemon** [comment]
@lorang92 @Magnusrm  This is now available as "[PopoverPanel](https://designsystem.altinn.studio/?path=/story/components-panel-popoverpanel--success)"
